# Generated by Django 5.2.1 on 2025-05-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=100, verbose_name='المسمى الوظيفي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=100, verbose_name='القسم/الإدارة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='locations.location', verbose_name='الموقع'),
        ),
    ]
