# Generated by Django 5.2.1 on 2025-05-24 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المجموعة')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الإهلاك')),
            ],
            options={
                'verbose_name': 'مجموعة أصول رئيسية',
                'verbose_name_plural': 'مجموعات الأصول الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الأصل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الأصل')),
                ('acquisition_date', models.DateField(verbose_name='تاريخ الاقتناء')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الاقتناء')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='القيمة التخريدية')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='العمر الإنتاجي (سنوات)')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('transferred', 'منقول'), ('disposed', 'مستبعد')], default='active', max_length=20, verbose_name='حالة الأصل')),
                ('depreciation_start_date', models.DateField(verbose_name='تاريخ بدء الإهلاك')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجمع الإهلاك')),
                ('last_depreciation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إهلاك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_in_custody', to='employees.employee', verbose_name='الموظف المسؤول')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='locations.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(verbose_name='تاريخ الاستبعاد')),
                ('disposal_type', models.CharField(choices=[('write_off', 'تكهين'), ('sale', 'بيع')], max_length=20, verbose_name='نوع الاستبعاد')),
                ('book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة الدفترية عند الاستبعاد')),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ البيع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='assets.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disposals', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'استبعاد أصل',
                'verbose_name_plural': 'استبعاد الأصول',
            },
        ),
        migrations.CreateModel(
            name='AssetSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة الفرعية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المجموعة الفرعية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory', verbose_name='المجموعة الرئيسية')),
            ],
            options={
                'verbose_name': 'مجموعة أصول فرعية',
                'verbose_name_plural': 'مجموعات الأصول الفرعية',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetsubcategory', verbose_name='المجموعة الفرعية'),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='تاريخ النقل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('from_custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='employees.employee', verbose_name='من الموظف')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='locations.branch', verbose_name='من الفرع')),
                ('to_custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='employees.employee', verbose_name='إلى الموظف')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='locations.branch', verbose_name='إلى الفرع')),
            ],
            options={
                'verbose_name': 'نقل أصل',
                'verbose_name_plural': 'نقل الأصول',
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='تاريخ الفترة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الإهلاك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'قيد إهلاك',
                'verbose_name_plural': 'قيود الإهلاك',
                'unique_together': {('asset', 'period_date')},
            },
        ),
    ]
