# Generated by Django 5.2.1 on 2025-05-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('type', models.CharField(choices=[('branch', 'فرع'), ('governorate', 'محافظة')], max_length=20, verbose_name='نوع الموقع')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='locations.location', verbose_name='الموقع الأب')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('locations.location',),
        ),
    ]
